version: "3.8"

services:
  shop-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shop_db
      SPRING_DATASOURCE_USERNAME: postgres   # Changed to 'postgres' to match the user in the postgres service
      SPRING_DATASOURCE_PASSWORD: password   # Keep the password consistent with the postgres service
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: shop_postgres
    restart: always
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
