# Stage 1: Build the React app
FROM node:16 AS client-build

WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the app source
COPY ./ ./

# Build the React app
RUN npm run build

# Stage 2: Serve the React app with Nginx
FROM nginx:1.23 AS client-serve

WORKDIR /usr/share/nginx/html

# Copy the React build files from the previous stage
COPY --from=client-build /app/build/ ./

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
